/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as DeliveryBulkRouteImport } from './routes/delivery.bulk'
import { Route as DeliveryNewRouteImport } from './routes/delivery.new'
import { Route as DeliveryOrdersRouteImport } from './routes/delivery.orders'
import { Route as DeliveryPickupPointsRouteImport } from './routes/delivery.pickup-points'
import { Route as DeliveryReceiversRouteImport } from './routes/delivery.receivers'
import { Route as DeliverySettingsRouteImport } from './routes/delivery.settings'
import { Route as DeliveryWalletRouteImport } from './routes/delivery.wallet'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ApiPublicMerchantSendPushRouteImport } from './routes/api/public/merchant-send-push'
import { Route as DeliveryTripIdRouteImport } from './routes/delivery.trip.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryBulkRoute = DeliveryBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryNewRoute = DeliveryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryOrdersRoute = DeliveryOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryPickupPointsRoute = DeliveryPickupPointsRouteImport.update({
  id: '/pickup-points',
  path: '/pickup-points',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryReceiversRoute = DeliveryReceiversRouteImport.update({
  id: '/receivers',
  path: '/receivers',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliverySettingsRoute = DeliverySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryWalletRoute = DeliveryWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DeliveryRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMerchantSendPushRoute =
  ApiPublicMerchantSendPushRouteImport.update({
    id: '/api/public/merchant-send-push',
    path: '/api/public/merchant-send-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryTripIdRoute = DeliveryTripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => DeliveryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/delivery/bulk': typeof DeliveryBulkRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/pickup-points': typeof DeliveryPickupPointsRoute
  '/delivery/receivers': typeof DeliveryReceiversRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/delivery/wallet': typeof DeliveryWalletRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/api/public/merchant-send-push': typeof ApiPublicMerchantSendPushRoute
  '/delivery/trip/$id': typeof DeliveryTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/delivery/bulk': typeof DeliveryBulkRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/pickup-points': typeof DeliveryPickupPointsRoute
  '/delivery/receivers': typeof DeliveryReceiversRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/delivery/wallet': typeof DeliveryWalletRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/delivery': typeof DeliveryIndexRoute
  '/api/public/merchant-send-push': typeof ApiPublicMerchantSendPushRoute
  '/delivery/trip/$id': typeof DeliveryTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/delivery/bulk': typeof DeliveryBulkRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/delivery/orders': typeof DeliveryOrdersRoute
  '/delivery/pickup-points': typeof DeliveryPickupPointsRoute
  '/delivery/receivers': typeof DeliveryReceiversRoute
  '/delivery/settings': typeof DeliverySettingsRoute
  '/delivery/wallet': typeof DeliveryWalletRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/api/public/merchant-send-push': typeof ApiPublicMerchantSendPushRoute
  '/delivery/trip/$id': typeof DeliveryTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delivery'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/rewards'
    | '/settings'
    | '/staff'
    | '/support'
    | '/wallet'
    | '/delivery/bulk'
    | '/delivery/new'
    | '/delivery/orders'
    | '/delivery/pickup-points'
    | '/delivery/receivers'
    | '/delivery/settings'
    | '/delivery/wallet'
    | '/legal/$slug'
    | '/delivery/'
    | '/api/public/merchant-send-push'
    | '/delivery/trip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/rewards'
    | '/settings'
    | '/staff'
    | '/support'
    | '/wallet'
    | '/delivery/bulk'
    | '/delivery/new'
    | '/delivery/orders'
    | '/delivery/pickup-points'
    | '/delivery/receivers'
    | '/delivery/settings'
    | '/delivery/wallet'
    | '/legal/$slug'
    | '/delivery'
    | '/api/public/merchant-send-push'
    | '/delivery/trip/$id'
  id:
    | '__root__'
    | '/'
    | '/delivery'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/rewards'
    | '/settings'
    | '/staff'
    | '/support'
    | '/wallet'
    | '/delivery/bulk'
    | '/delivery/new'
    | '/delivery/orders'
    | '/delivery/pickup-points'
    | '/delivery/receivers'
    | '/delivery/settings'
    | '/delivery/wallet'
    | '/legal/$slug'
    | '/delivery/'
    | '/api/public/merchant-send-push'
    | '/delivery/trip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SupportRoute: typeof SupportRoute
  WalletRoute: typeof WalletRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiPublicMerchantSendPushRoute: typeof ApiPublicMerchantSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/bulk': {
      id: '/delivery/bulk'
      path: '/bulk'
      fullPath: '/delivery/bulk'
      preLoaderRoute: typeof DeliveryBulkRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/new': {
      id: '/delivery/new'
      path: '/new'
      fullPath: '/delivery/new'
      preLoaderRoute: typeof DeliveryNewRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/orders': {
      id: '/delivery/orders'
      path: '/orders'
      fullPath: '/delivery/orders'
      preLoaderRoute: typeof DeliveryOrdersRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/pickup-points': {
      id: '/delivery/pickup-points'
      path: '/pickup-points'
      fullPath: '/delivery/pickup-points'
      preLoaderRoute: typeof DeliveryPickupPointsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/receivers': {
      id: '/delivery/receivers'
      path: '/receivers'
      fullPath: '/delivery/receivers'
      preLoaderRoute: typeof DeliveryReceiversRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/settings': {
      id: '/delivery/settings'
      path: '/settings'
      fullPath: '/delivery/settings'
      preLoaderRoute: typeof DeliverySettingsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/wallet': {
      id: '/delivery/wallet'
      path: '/wallet'
      fullPath: '/delivery/wallet'
      preLoaderRoute: typeof DeliveryWalletRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/merchant-send-push': {
      id: '/api/public/merchant-send-push'
      path: '/api/public/merchant-send-push'
      fullPath: '/api/public/merchant-send-push'
      preLoaderRoute: typeof ApiPublicMerchantSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/trip/$id': {
      id: '/delivery/trip/$id'
      path: '/trip/$id'
      fullPath: '/delivery/trip/$id'
      preLoaderRoute: typeof DeliveryTripIdRouteImport
      parentRoute: typeof DeliveryRoute
    }
  }
}

interface DeliveryRouteChildren {
  DeliveryBulkRoute: typeof DeliveryBulkRoute
  DeliveryNewRoute: typeof DeliveryNewRoute
  DeliveryOrdersRoute: typeof DeliveryOrdersRoute
  DeliveryPickupPointsRoute: typeof DeliveryPickupPointsRoute
  DeliveryReceiversRoute: typeof DeliveryReceiversRoute
  DeliverySettingsRoute: typeof DeliverySettingsRoute
  DeliveryWalletRoute: typeof DeliveryWalletRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
  DeliveryTripIdRoute: typeof DeliveryTripIdRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryBulkRoute: DeliveryBulkRoute,
  DeliveryNewRoute: DeliveryNewRoute,
  DeliveryOrdersRoute: DeliveryOrdersRoute,
  DeliveryPickupPointsRoute: DeliveryPickupPointsRoute,
  DeliveryReceiversRoute: DeliveryReceiversRoute,
  DeliverySettingsRoute: DeliverySettingsRoute,
  DeliveryWalletRoute: DeliveryWalletRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
  DeliveryTripIdRoute: DeliveryTripIdRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SupportRoute: SupportRoute,
  WalletRoute: WalletRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiPublicMerchantSendPushRoute: ApiPublicMerchantSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
